# frozen_string_literal: true

source 'https://rubygems.org'

gem 'telegram-bot-ruby', '~> 1.0'

# gem 'pg', '~> 1.4.5'
gem 'pg', '~> 1.5', '>= 1.5.3'

gem 'activerecord'

gem 'aasm', '~> 5.1', '>= 5.1.1'


gem 'faraday'

gem 'faraday-multipart'

gem 'nokogiri'


gem 'ruby-debug-ide'
# gem 'debase'