# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'telegram-bot-ruby', '~> 0.23.0'
gem "pg", "~> 1.1"
gem 'activerecord'
gem 'aasm', '~> 5.1', '>= 5.1.1'
gem 'colorize'
gem 'redis'