# frozen_string_literal: true

desc 'starting polling main bot && starting pollint moderator bot && starting redis-listener'
task :start do
  main_path      = "#{__dir__}/bot-main/polling-main.rb"
  moderator_path = "#{__dir__}/bot-moderator/polling-mod.rb"
  redis_path     = "#{__dir__}/redis/redis-listener.rb"
  system("(bundle exec ruby #{main_path} &)")      # main bot
  system("(bundle exec ruby #{moderator_path} &)") # moderabor bot
  system("(bundle exec ruby #{redis_path} &)")     # redis
end

desc 'killing pids bots && redis'
task :stop do
  pids_file_path = "#{__dir__}/tmp/pids.txt"
  pids_file = File.readlines(pids_file_path).each do |pid|
    system("kill -9 #{pid}")
  end
  FileUtils.rm(pids_file_path)
end

desc 'stop + start'
task :restart do
  system('rake stop')
  system('rake start')
end
