

source 'https://rubygems.org'

# gem "rails"
gem 'aasm', '~> 5.1', '>= 5.1.1'
gem 'activerecord'
gem 'colorize'
# gem 'pg', '~> 1.1'
gem 'pg', '~> 1.5', '>= 1.5.3'
# gem 'redis'
gem 'telegram-bot-ruby', '~> 0.23.0'


gem 'ruby-debug-ide'
# gem 'debase'