root = ENV['Garant_Bots_Path']


def kill_pid pids_file_path
  pids_file = File.readlines(pids_file_path).each do |pid|
    system("kill -9 #{pid}")
  end
  FileUtils.rm(pids_file_path)
end

desc 'starting main bot && starting moderator bot && starting redis-listener'
task :start do
  main_path      = "#{root}/main.rb"
  moderator_path = "#{root}/moderator.rb"
  system("(bundle exec ruby #{main_path} &)")      # main bot
  system("(bundle exec ruby #{moderator_path} &)") # moderabor bot
end

desc 'killing pids bots'
task :stop do
  main_file_path = "#{root}/tmp/main.pid"
  moderator_file_path = "#{root}/tmp/moderator.pid"
  kill_pid(main_file_path)
  kill_pid(moderator_file_path)
end

desc 'stop + start'
task :restart do
  system('rake stop')
  system('rake start')
end
