# frozen_string_literal: true
main_path      = "#{__dir__}/main.rb"
moderator_path = "#{__dir__}/moderator.rb"

main_pid_file_path      = "#{__dir__}/tmp/main.pid"
moderator_pid_file_path = "#{__dir__}/tmp/moderator.pid"

def stopping pid_path
    File.readlines(pid_path).each do |pid|
        system("kill -9 #{pid}")
    end
    FileUtils.rm(pid_path)
    rescue 
end


desc 'starting black-list-bot && starting black-list-moderator-bot'
task :start do
  system("(bundle exec ruby #{main_path} &)")      # main bot
  system("(bundle exec ruby #{moderator_path} &)") # moderabor bot
end

desc 'killing pids bots && redis'
task :stop do  
    stopping(main_pid_file_path)
    stopping(moderator_pid_file_path)
end

desc 'stop + start'
task :restart do
  system('rake stop')
  system('rake start')
end
