# frozen_string_literal: true

source 'https://rubygems.org'

gem 'telegram-bot-ruby', '~> 1.0'

gem 'pg', '~> 1.4.5'

gem 'activerecord'

gem 'aasm', '~> 5.1', '>= 5.1.1'

gem 'ruby-debug-ide'

# can't find executable rdebug-ide for gem ruby-debug-ide. ruby-debug-ide
